import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';


class AppTheme {

  static const Map<String, ColorScheme> colorSchemes = {
    'blue': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF0061A4),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD1E4FF),
      onPrimaryContainer: Color(0xFF001D36),
      secondary: Color(0xFF535F70),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD7E3F7),
      onSecondaryContainer: Color(0xFF101C2B),
      tertiary: Color(0xFF6B5778),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF2DAFF),
      onTertiaryContainer: Color(0xFF251431),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFDFCFF),
      onBackground: Color(0xFF1A1C1E),
      surface: Color(0xFFFDFCFF),
      onSurface: Color(0xFF1A1C1E),
      surfaceVariant: Color(0xFFDFE2EB),
      onSurfaceVariant: Color(0xFF43474E),
      outline: Color(0xFF73777F),
      outlineVariant: Color(0xFFC3C7CF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2F3033),
      onInverseSurface: Color(0xFFF1F0F4),
      inversePrimary: Color(0xFF9ECAFF),
    ),
    'green': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006E26),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF96F79D),
      onPrimaryContainer: Color(0xFF002106),
      secondary: Color(0xFF526350),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD5E8D0),
      onSecondaryContainer: Color(0xFF101F10),
      tertiary: Color(0xFF39656B),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFBCEBF2),
      onTertiaryContainer: Color(0xFF001F23),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFCFDF7),
      onBackground: Color(0xFF1A1C19),
      surface: Color(0xFFFCFDF7),
      onSurface: Color(0xFF1A1C19),
      surfaceVariant: Color(0xFFDEE5D9),
      onSurfaceVariant: Color(0xFF424940),
      outline: Color(0xFF72796F),
      outlineVariant: Color(0xFFC2C9BD),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2F312D),
      onInverseSurface: Color(0xFFF1F1EB),
      inversePrimary: Color(0xFF7BDA83),
    ),
    'purple': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF6750A4),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFEADDFF),
      onPrimaryContainer: Color(0xFF21005D),
      secondary: Color(0xFF625B71),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE8DEF8),
      onSecondaryContainer: Color(0xFF1D192B),
      tertiary: Color(0xFF7D5260),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD8E4),
      onTertiaryContainer: Color(0xFF31111D),
      error: Color(0xFFB3261E),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFF9DEDC),
      onErrorContainer: Color(0xFF410E0B),
      background: Color(0xFFFFFBFE),
      onBackground: Color(0xFF1C1B1F),
      surface: Color(0xFFFFFBFE),
      onSurface: Color(0xFF1C1B1F),
      surfaceVariant: Color(0xFFE7E0EC),
      onSurfaceVariant: Color(0xFF49454F),
      outline: Color(0xFF79747E),
      outlineVariant: Color(0xFFCAC4D0),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF313033),
      onInverseSurface: Color(0xFFF4EFF4),
      inversePrimary: Color(0xFFD0BCFF),
    ),
    'orange': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFB3270D),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDAD4),
      onPrimaryContainer: Color(0xFF3D0700),
      secondary: Color(0xFF77574E),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDAD4),
      onSecondaryContainer: Color(0xFF2C150F),
      tertiary: Color(0xFF6C5D2F),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF5E1A7),
      onTertiaryContainer: Color(0xFF231B00),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A19),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A19),
      surfaceVariant: Color(0xFFF5DED8),
      onSurfaceVariant: Color(0xFF53433F),
      outline: Color(0xFF85736E),
      outlineVariant: Color(0xFFD8C2BC),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF362F2D),
      onInverseSurface: Color(0xFFFBEEEB),
      inversePrimary: Color(0xFFFFB4A8),
    ),
    'pink': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFC00058),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFD9E2),
      onPrimaryContainer: Color(0xFF3E001A),
      secondary: Color(0xFF74565F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFD9E2),
      onSecondaryContainer: Color(0xFF2B151C),
      tertiary: Color(0xFF7C5635),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDCC1),
      onTertiaryContainer: Color(0xFF2E1500),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A1B),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A1B),
      surfaceVariant: Color(0xFFF2DDE1),
      onSurfaceVariant: Color(0xFF514347),
      outline: Color(0xFF837377),
      outlineVariant: Color(0xFFD5C2C6),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF352F30),
      onInverseSurface: Color(0xFFFAEEEF),
      inversePrimary: Color(0xFFFFB0C8),
    ),
    'teal': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006A60),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF74F8E4),
      onPrimaryContainer: Color(0xFF00201C),
      secondary: Color(0xFF4A635F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFCCE8E2),
      onSecondaryContainer: Color(0xFF05201C),
      tertiary: Color(0xFF45617A),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFCCE5FF),
      onTertiaryContainer: Color(0xFF001E32),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFAFDFB),
      onBackground: Color(0xFF191C1B),
      surface: Color(0xFFFAFDFB),
      onSurface: Color(0xFF191C1B),
      surfaceVariant: Color(0xFFDAE5E1),
      onSurfaceVariant: Color(0xFF3F4946),
      outline: Color(0xFF6F7976),
      outlineVariant: Color(0xFFBEC9C5),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2D3130),
      onInverseSurface: Color(0xFFEFF1EF),
      inversePrimary: Color(0xFF52DBC8),
    ),
    'indigo': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF4355B9),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFDDE1FF),
      onPrimaryContainer: Color(0xFF00105C),
      secondary: Color(0xFF5A5D72),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFDFE1F9),
      onSecondaryContainer: Color(0xFF171B2C),
      tertiary: Color(0xFF76546E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD7F4),
      onTertiaryContainer: Color(0xFF2D1228),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFEFBFF),
      onBackground: Color(0xFF1B1B1F),
      surface: Color(0xFFFEFBFF),
      onSurface: Color(0xFF1B1B1F),
      surfaceVariant: Color(0xFFE2E1EC),
      onSurfaceVariant: Color(0xFF45464F),
      outline: Color(0xFF767680),
      outlineVariant: Color(0xFFC6C5D0),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF303034),
      onInverseSurface: Color(0xFFF2F0F4),
      inversePrimary: Color(0xFFB9C3FF),
    ),
    'red': ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFC00100),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDAD4),
      onPrimaryContainer: Color(0xFF410000),
      secondary: Color(0xFF775651),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDAD4),
      onSecondaryContainer: Color(0xFF2C1511),
      tertiary: Color(0xFF6F5C2E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFAE0A6),
      onTertiaryContainer: Color(0xFF251A00),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A19),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A19),
      surfaceVariant: Color(0xFFF5DDD9),
      onSurfaceVariant: Color(0xFF534341),
      outline: Color(0xFF857370),
      outlineVariant: Color(0xFFD8C2BD),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF362F2D),
      onInverseSurface: Color(0xFFFBEEEB),
      inversePrimary: Color(0xFFFFB4A8),
    ),
  };

  static const Map<String, ColorScheme> darkColorSchemes = {
    'blue': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF9ECAFF),
      onPrimary: Color(0xFF003258),
      primaryContainer: Color(0xFF00497D),
      onPrimaryContainer: Color(0xFFD1E4FF),
      secondary: Color(0xFFBBC7DB),
      onSecondary: Color(0xFF253140),
      secondaryContainer: Color(0xFF3B4858),
      onSecondaryContainer: Color(0xFFD7E3F7),
      tertiary: Color(0xFFD6BEE4),
      onTertiary: Color(0xFF3B2948),
      tertiaryContainer: Color(0xFF523F5F),
      onTertiaryContainer: Color(0xFFF2DAFF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1A1C1E),
      onBackground: Color(0xFFE2E2E6),
      surface: Color(0xFF1A1C1E),
      onSurface: Color(0xFFE2E2E6),
      surfaceVariant: Color(0xFF43474E),
      onSurfaceVariant: Color(0xFFC3C7CF),
      outline: Color(0xFF8D9199),
      outlineVariant: Color(0xFF43474E),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE2E2E6),
      onInverseSurface: Color(0xFF1A1C1E),
      inversePrimary: Color(0xFF0061A4),
    ),
    'green': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF7BDA83),
      onPrimary: Color(0xFF003910),
      primaryContainer: Color(0xFF00531B),
      onPrimaryContainer: Color(0xFF96F79D),
      secondary: Color(0xFFB9CCB4),
      onSecondary: Color(0xFF243424),
      secondaryContainer: Color(0xFF3A4B39),
      onSecondaryContainer: Color(0xFFD5E8D0),
      tertiary: Color(0xFFA1CED5),
      onTertiary: Color(0xFF00363C),
      tertiaryContainer: Color(0xFF1F4D53),
      onTertiaryContainer: Color(0xFFBCEBF2),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1A1C19),
      onBackground: Color(0xFFE2E3DD),
      surface: Color(0xFF1A1C19),
      onSurface: Color(0xFFE2E3DD),
      surfaceVariant: Color(0xFF424940),
      onSurfaceVariant: Color(0xFFC2C9BD),
      outline: Color(0xFF8C9388),
      outlineVariant: Color(0xFF424940),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE2E3DD),
      onInverseSurface: Color(0xFF1A1C19),
      inversePrimary: Color(0xFF006E26),
    ),
    'purple': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD0BCFF),
      onPrimary: Color(0xFF381E72),
      primaryContainer: Color(0xFF4F378B),
      onPrimaryContainer: Color(0xFFEADDFF),
      secondary: Color(0xFFCCC2DC),
      onSecondary: Color(0xFF332D41),
      secondaryContainer: Color(0xFF4A4458),
      onSecondaryContainer: Color(0xFFE8DEF8),
      tertiary: Color(0xFFEFB8C8),
      onTertiary: Color(0xFF492532),
      tertiaryContainer: Color(0xFF633B48),
      onTertiaryContainer: Color(0xFFFFD8E4),
      error: Color(0xFFF2B8B5),
      onError: Color(0xFF601410),
      errorContainer: Color(0xFF8C1D18),
      onErrorContainer: Color(0xFFF9DEDC),
      background: Color(0xFF1C1B1F),
      onBackground: Color(0xFFE6E1E5),
      surface: Color(0xFF1C1B1F),
      onSurface: Color(0xFFE6E1E5),
      surfaceVariant: Color(0xFF49454F),
      onSurfaceVariant: Color(0xFFCAC4D0),
      outline: Color(0xFF938F99),
      outlineVariant: Color(0xFF49454F),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE6E1E5),
      onInverseSurface: Color(0xFF1C1B1F),
      inversePrimary: Color(0xFF6750A4),
    ),
    'orange': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB4A8),
      onPrimary: Color(0xFF690100),
      primaryContainer: Color(0xFF930100),
      onPrimaryContainer: Color(0xFFFFDAD4),
      secondary: Color(0xFFE7BDB6),
      onSecondary: Color(0xFF442A23),
      secondaryContainer: Color(0xFF5D3F38),
      onSecondaryContainer: Color(0xFFFFDAD4),
      tertiary: Color(0xFFD8C58D),
      onTertiary: Color(0xFF3B2F05),
      tertiaryContainer: Color(0xFF53451A),
      onTertiaryContainer: Color(0xFFF5E1A7),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A19),
      onBackground: Color(0xFFEDE0DD),
      surface: Color(0xFF201A19),
      onSurface: Color(0xFFEDE0DD),
      surfaceVariant: Color(0xFF53433F),
      onSurfaceVariant: Color(0xFFD8C2BC),
      outline: Color(0xFFA08D87),
      outlineVariant: Color(0xFF53433F),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFEDE0DD),
      onInverseSurface: Color(0xFF201A19),
      inversePrimary: Color(0xFFB3270D),
    ),
    'pink': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB0C8),
      onPrimary: Color(0xFF65002E),
      primaryContainer: Color(0xFF8E0044),
      onPrimaryContainer: Color(0xFFFFD9E2),
      secondary: Color(0xFFE2BDC6),
      onSecondary: Color(0xFF422931),
      secondaryContainer: Color(0xFF5A3F47),
      onSecondaryContainer: Color(0xFFFFD9E2),
      tertiary: Color(0xFFEFBD94),
      onTertiary: Color(0xFF48290C),
      tertiaryContainer: Color(0xFF613F20),
      onTertiaryContainer: Color(0xFFFFDCC1),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A1B),
      onBackground: Color(0xFFECE0E1),
      surface: Color(0xFF201A1B),
      onSurface: Color(0xFFECE0E1),
      surfaceVariant: Color(0xFF514347),
      onSurfaceVariant: Color(0xFFD5C2C6),
      outline: Color(0xFF9E8C90),
      outlineVariant: Color(0xFF514347),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFECE0E1),
      onInverseSurface: Color(0xFF201A1B),
      inversePrimary: Color(0xFFC00058),
    ),
    'teal': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF52DBC8),
      onPrimary: Color(0xFF003731),
      primaryContainer: Color(0xFF005048),
      onPrimaryContainer: Color(0xFF74F8E4),
      secondary: Color(0xFFB0CCC6),
      onSecondary: Color(0xFF1B3531),
      secondaryContainer: Color(0xFF324B47),
      onSecondaryContainer: Color(0xFFCCE8E2),
      tertiary: Color(0xFFAFC9E3),
      onTertiary: Color(0xFF173349),
      tertiaryContainer: Color(0xFF2E4961),
      onTertiaryContainer: Color(0xFFCCE5FF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF191C1B),
      onBackground: Color(0xFFE0E3E1),
      surface: Color(0xFF191C1B),
      onSurface: Color(0xFFE0E3E1),
      surfaceVariant: Color(0xFF3F4946),
      onSurfaceVariant: Color(0xFFBEC9C5),
      outline: Color(0xFF89938F),
      outlineVariant: Color(0xFF3F4946),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE0E3E1),
      onInverseSurface: Color(0xFF191C1B),
      inversePrimary: Color(0xFF006A60),
    ),
    'indigo': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFB9C3FF),
      onPrimary: Color(0xFF0A2478),
      primaryContainer: Color(0xFF293D9F),
      onPrimaryContainer: Color(0xFFDDE1FF),
      secondary: Color(0xFFC3C5DD),
      onSecondary: Color(0xFF2C2F42),
      secondaryContainer: Color(0xFF434659),
      onSecondaryContainer: Color(0xFFDFE1F9),
      tertiary: Color(0xFFE6B9D8),
      onTertiary: Color(0xFF44263D),
      tertiaryContainer: Color(0xFF5D3C55),
      onTertiaryContainer: Color(0xFFFFD7F4),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1B1B1F),
      onBackground: Color(0xFFE3E1E9),
      surface: Color(0xFF1B1B1F),
      onSurface: Color(0xFFE3E1E9),
      surfaceVariant: Color(0xFF45464F),
      onSurfaceVariant: Color(0xFFC6C5D0),
      outline: Color(0xFF8F909A),
      outlineVariant: Color(0xFF45464F),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE3E1E9),
      onInverseSurface: Color(0xFF1B1B1F),
      inversePrimary: Color(0xFF4355B9),
    ),
    'red': ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB4A8),
      onPrimary: Color(0xFF690000),
      primaryContainer: Color(0xFF930100),
      onPrimaryContainer: Color(0xFFFFDAD4),
      secondary: Color(0xFFE7BDB6),
      onSecondary: Color(0xFF442A25),
      secondaryContainer: Color(0xFF5D3F3A),
      onSecondaryContainer: Color(0xFFFFDAD4),
      tertiary: Color(0xFFDCC48C),
      onTertiary: Color(0xFF3D2E04),
      tertiaryContainer: Color(0xFF554419),
      onTertiaryContainer: Color(0xFFFAE0A6),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A19),
      onBackground: Color(0xFFEDE0DD),
      surface: Color(0xFF201A19),
      onSurface: Color(0xFFEDE0DD),
      surfaceVariant: Color(0xFF534341),
      onSurfaceVariant: Color(0xFFD8C2BD),
      outline: Color(0xFFA08D88),
      outlineVariant: Color(0xFF534341),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFEDE0DD),
      onInverseSurface: Color(0xFF201A19),
      inversePrimary: Color(0xFFC00100),
    ),
  };

  static ThemeData lightTheme(String colorSchemeName) {
    final colorScheme = colorSchemes[colorSchemeName] ?? colorSchemes['blue']!;

    return ThemeData(
      useMaterial3: true,
      colorScheme: colorScheme,
      textTheme: GoogleFonts.interTextTheme(),
      appBarTheme: AppBarTheme(
        centerTitle: false,
        elevation: 0,
        backgroundColor: colorScheme.surface,
        foregroundColor: colorScheme.onSurface,
        titleTextStyle: GoogleFonts.inter(
          fontSize: 20,
          fontWeight: FontWeight.w600,
          color: colorScheme.onSurface,
        ),
      ),
      cardTheme: CardTheme(
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
        color: colorScheme.surfaceVariant.withOpacity(0.3),
      ),

      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          elevation: 0,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: colorScheme.surfaceVariant.withOpacity(0.3),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: colorScheme.primary, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      ),
      chipTheme: ChipThemeData(
        backgroundColor: colorScheme.primaryContainer,
        labelStyle: TextStyle(color: colorScheme.onPrimaryContainer),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        elevation: 2,
        backgroundColor: colorScheme.primaryContainer,
        foregroundColor: colorScheme.onPrimaryContainer,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
        ),
      ),
    );
  }

  static ThemeData darkTheme(String colorSchemeName) {
    final colorScheme = darkColorSchemes[colorSchemeName] ?? darkColorSchemes['blue']!;

    return ThemeData(
      useMaterial3: true,
      colorScheme: colorScheme,
      textTheme: GoogleFonts.interTextTheme(ThemeData.dark().textTheme),
      appBarTheme: AppBarTheme(
        centerTitle: false,
        elevation: 0,
        backgroundColor: colorScheme.surface,
        foregroundColor: colorScheme.onSurface,
        titleTextStyle: GoogleFonts.inter(
          fontSize: 20,
          fontWeight: FontWeight.w600,
          color: colorScheme.onSurface,
        ),
      ),
      cardTheme: CardTheme(
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
        color: colorScheme.surfaceVariant.withOpacity(0.3),
      ),

      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          elevation: 0,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: colorScheme.surfaceVariant.withOpacity(0.3),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: colorScheme.primary, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      ),
      chipTheme: ChipThemeData(
        backgroundColor: colorScheme.primaryContainer,
        labelStyle: TextStyle(color: colorScheme.onPrimaryContainer),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        elevation: 2,
        backgroundColor: colorScheme.primaryContainer,
        foregroundColor: colorScheme.onPrimaryContainer,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
        ),
      ),
    );
  }
}